# Generated by Django 2.2 on 2020-07-07 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='names',
            name='activity_periods',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='acuser.Periods'),
        ),
    ]
