# Generated by Django 2.2 on 2020-07-07 16:24

import datetime
from django.db import migrations
import timezone_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('acuser', '0002_auto_20200707_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periods',
            name='end',
            field=timezone_utils.fields.LinkedTZDateTimeField(max_length=10, time_override=datetime.time(23, 59, 59, 999999)),
        ),
        migrations.AlterField(
            model_name='periods',
            name='start',
            field=timezone_utils.fields.LinkedTZDateTimeField(max_length=10, time_override=datetime.time(0, 0)),
        ),
    ]
