# Generated by Django 2.2 on 2020-07-07 16:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import timezone_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('acuser', '0003_auto_20200707_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='End',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', timezone_utils.fields.LinkedTZDateTimeField(time_override=datetime.time(0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', timezone_utils.fields.LinkedTZDateTimeField(time_override=datetime.time(0, 0))),
            ],
        ),
        migrations.AlterField(
            model_name='periods',
            name='end',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='acuser.End'),
        ),
        migrations.AlterField(
            model_name='periods',
            name='start',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='acuser.Start'),
        ),
    ]
