# Generated by Django 2.2 on 2020-07-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuser', '0005_auto_20200707_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='names',
            name='activity_periods',
        ),
        migrations.AddField(
            model_name='names',
            name='activity_periods',
            field=models.ManyToManyField(to='acuser.Periods'),
        ),
    ]
